/* Langy vocabulary — ages 5–7, single file */
const LETTER_ITEMS = [
  {
    "word": "a",
    "letter": "A",
    "emoji": "🍎",
    "line": "A IS FOR APPLE"
  },
  {
    "word": "b",
    "letter": "B",
    "emoji": "🐻",
    "line": "B IS FOR BEAR"
  },
  {
    "word": "c",
    "letter": "C",
    "emoji": "🐱",
    "line": "C IS FOR CAT"
  },
  {
    "word": "d",
    "letter": "D",
    "emoji": "🐶",
    "line": "D IS FOR DOG"
  },
  {
    "word": "e",
    "letter": "E",
    "emoji": "🐘",
    "line": "E IS FOR ELEPHANT"
  },
  {
    "word": "f",
    "letter": "F",
    "emoji": "🐟",
    "line": "F IS FOR FISH"
  },
  {
    "word": "g",
    "letter": "G",
    "emoji": "🍇",
    "line": "G IS FOR GRAPES"
  },
  {
    "word": "h",
    "letter": "H",
    "emoji": "🏠",
    "line": "H IS FOR HOUSE"
  },
  {
    "word": "i",
    "letter": "I",
    "emoji": "🧊",
    "line": "I IS FOR ICE"
  },
  {
    "word": "j",
    "letter": "J",
    "emoji": "🧃",
    "line": "J IS FOR JUICE"
  },
  {
    "word": "k",
    "letter": "K",
    "emoji": "🪁",
    "line": "K IS FOR KITE"
  },
  {
    "word": "l",
    "letter": "L",
    "emoji": "🦁",
    "line": "L IS FOR LION"
  },
  {
    "word": "m",
    "letter": "M",
    "emoji": "🌙",
    "line": "M IS FOR MOON"
  },
  {
    "word": "n",
    "letter": "N",
    "emoji": "🪺",
    "line": "N IS FOR NEST"
  },
  {
    "word": "o",
    "letter": "O",
    "emoji": "🍊",
    "line": "O IS FOR ORANGE"
  },
  {
    "word": "p",
    "letter": "P",
    "emoji": "🐷",
    "line": "P IS FOR PIG"
  },
  {
    "word": "q",
    "letter": "Q",
    "emoji": "👑",
    "line": "Q IS FOR QUEEN"
  },
  {
    "word": "r",
    "letter": "R",
    "emoji": "🐰",
    "line": "R IS FOR RABBIT"
  },
  {
    "word": "s",
    "letter": "S",
    "emoji": "☀️",
    "line": "S IS FOR SUN"
  },
  {
    "word": "t",
    "letter": "T",
    "emoji": "🌳",
    "line": "T IS FOR TREE"
  },
  {
    "word": "u",
    "letter": "U",
    "emoji": "☂️",
    "line": "U IS FOR UMBRELLA"
  },
  {
    "word": "v",
    "letter": "V",
    "emoji": "🎻",
    "line": "V IS FOR VIOLIN"
  },
  {
    "word": "w",
    "letter": "W",
    "emoji": "💧",
    "line": "W IS FOR WATER"
  },
  {
    "word": "x",
    "letter": "X",
    "emoji": "🩻",
    "line": "X IS FOR X-RAY"
  },
  {
    "word": "y",
    "letter": "Y",
    "emoji": "🪀",
    "line": "Y IS FOR YO-YO"
  },
  {
    "word": "z",
    "letter": "Z",
    "emoji": "🦓",
    "line": "Z IS FOR ZEBRA"
  }
];

const DIGIT_ITEMS = [
  {
    "word": "zero",
    "digit": "0",
    "emoji": "0️⃣",
    "line": "ZERO EGGS IN THE BOX!"
  },
  {
    "word": "one",
    "digit": "1",
    "emoji": "1️⃣",
    "line": "ONE LITTLE STAR!"
  },
  {
    "word": "two",
    "digit": "2",
    "emoji": "2️⃣",
    "line": "TWO HANDS!"
  },
  {
    "word": "three",
    "digit": "3",
    "emoji": "3️⃣",
    "line": "THREE BEARS!"
  },
  {
    "word": "four",
    "digit": "4",
    "emoji": "4️⃣",
    "line": "FOUR WHEELS!"
  },
  {
    "word": "five",
    "digit": "5",
    "emoji": "5️⃣",
    "line": "HIGH FIVE!"
  },
  {
    "word": "six",
    "digit": "6",
    "emoji": "6️⃣",
    "line": "SIX EGGS!"
  },
  {
    "word": "seven",
    "digit": "7",
    "emoji": "7️⃣",
    "line": "SEVEN COLORS!"
  },
  {
    "word": "eight",
    "digit": "8",
    "emoji": "8️⃣",
    "line": "EIGHT LEGS ON A SPIDER!"
  },
  {
    "word": "nine",
    "digit": "9",
    "emoji": "9️⃣",
    "line": "NINE BALLOONS!"
  },
  {
    "word": "ten",
    "digit": "10",
    "emoji": "🔟",
    "line": "TEN FINGERS!"
  }
];

function pack(rows) {
  return rows.map(([word, emoji, line]) => ({
    word: word.toLowerCase(),
    emoji,
    line,
  }));
}

const LESSONS = {
  letters: { label: "LETTERS", icon: "🔤", kind: "letters", items: LETTER_ITEMS },
  digits: { label: "DIGITS", icon: "🔢", kind: "digits", items: DIGIT_ITEMS },
  numbers: { label: "NUMBERS", icon: "🧮", kind: "words", items: DIGIT_ITEMS.filter((d) => d.digit !== "0" && d.digit !== "10") },
  animals: {
    label: "ANIMALS",
    icon: "🐾",
    kind: "words",
    items: [
    { word: "cat", emoji: "🐱", line: "THE CAT SAYS MEOW!" },
    { word: "dog", emoji: "🐶", line: "THE DOG SAYS WOOF!" },
    { word: "bird", emoji: "🐦", line: "THE BIRD CAN FLY!" },
    { word: "fish", emoji: "🐟", line: "THE FISH SWIMS!" },
    { word: "cow", emoji: "🐮", line: "THE COW SAYS MOO!" },
    { word: "pig", emoji: "🐷", line: "THE PIG SAYS OINK!" },
    { word: "duck", emoji: "🦆", line: "THE DUCK SAYS QUACK!" },
    { word: "frog", emoji: "🐸", line: "THE FROG SAYS RIBBIT!" },
    { word: "lion", emoji: "🦁", line: "THE LION ROARS!" },
    { word: "tiger", emoji: "🐯", line: "THE TIGER HAS STRIPES!" },
    { word: "bear", emoji: "🐻", line: "THE BEAR IS BIG AND FUZZY!" },
    { word: "horse", emoji: "🐴", line: "THE HORSE RUNS FAST!" },
    { word: "sheep", emoji: "🐑", line: "THE SHEEP SAYS BAA!" },
    { word: "goat", emoji: "🐐", line: "THE GOAT CLIMBS ROCKS!" },
    { word: "chicken", emoji: "🐔", line: "THE CHICKEN SAYS CLUCK!" },
    { word: "rabbit", emoji: "🐰", line: "THE RABBIT HOPS!" },
    { word: "mouse", emoji: "🐭", line: "THE MOUSE IS SMALL!" },
    { word: "elephant", emoji: "🐘", line: "THE ELEPHANT IS HUGE!" },
    { word: "giraffe", emoji: "🦒", line: "THE GIRAFFE HAS A LONG NECK!" },
    { word: "zebra", emoji: "🦓", line: "THE ZEBRA HAS STRIPES!" },
    { word: "monkey", emoji: "🐵", line: "THE MONKEY SWINGS!" },
    { word: "panda", emoji: "🐼", line: "THE PANDA LOVES BAMBOO!" },
    { word: "koala", emoji: "🐨", line: "THE KOALA SLEEPS IN TREES!" },
    { word: "owl", emoji: "🦉", line: "THE OWL SAYS WHO!" },
    { word: "bee", emoji: "🐝", line: "THE BEE BUZZES!" },
    { word: "butterfly", emoji: "🦋", line: "THE BUTTERFLY IS COLORFUL!" },
    { word: "snake", emoji: "🐍", line: "THE SNAKE SLITHERS!" },
    { word: "turtle", emoji: "🐢", line: "THE TURTLE IS SLOW!" },
    { word: "whale", emoji: "🐋", line: "THE WHALE IS ENORMOUS!" },
    { word: "dolphin", emoji: "🐬", line: "THE DOLPHIN JUMPS!" },
    { word: "shark", emoji: "🦈", line: "THE SHARK SWIMS IN THE SEA!" },
    { word: "crab", emoji: "🦀", line: "THE CRAB WALKS SIDEWAYS!" },
    { word: "penguin", emoji: "🐧", line: "THE PENGUIN LOVES ICE!" },
    { word: "fox", emoji: "🦊", line: "THE FOX IS CLEVER!" },
    { word: "wolf", emoji: "🐺", line: "THE WOLF HOWLS!" },
    { word: "deer", emoji: "🦌", line: "THE DEER RUNS IN THE FOREST!" },
    { word: "squirrel", emoji: "🐿️", line: "THE SQUIRREL LOVES NUTS!" },
    { word: "bat", emoji: "🦇", line: "THE BAT FLIES AT NIGHT!" },
    { word: "snail", emoji: "🐌", line: "THE SNAIL CARRIES A SHELL!" },
    { word: "octopus", emoji: "🐙", line: "THE OCTOPUS HAS EIGHT ARMS!" },
    { word: "hippo", emoji: "🦛", line: "THE HIPPO LOVES WATER!" },
    { word: "rhino", emoji: "🦏", line: "THE RHINO HAS A BIG HORN!" },
    { word: "camel", emoji: "🐫", line: "THE CAMEL LIVES IN THE DESERT!" },
    { word: "kangaroo", emoji: "🦘", line: "THE KANGAROO JUMPS HIGH!" },
    { word: "parrot", emoji: "🦜", line: "THE PARROT CAN TALK!" },
    { word: "ant", emoji: "🐜", line: "THE ANT IS TINY BUT STRONG!" },
    { word: "ladybug", emoji: "🐞", line: "THE LADYBUG HAS SPOTS!" },
    ],
  },
  pets: {
    label: "PETS",
    icon: "🐹",
    kind: "words",
    items: [
    { word: "puppy", emoji: "🐶", line: "PLAYFUL PUPPY!" },
    { word: "kitten", emoji: "🐱", line: "CUTE KITTEN!" },
    { word: "hamster", emoji: "🐹", line: "TINY HAMSTER!" },
    { word: "goldfish", emoji: "🐠", line: "SWIMMING GOLDFISH!" },
    { word: "parrot", emoji: "🦜", line: "TALKING PARROT!" },
    ],
  },
  farm: {
    label: "FARM",
    icon: "🚜",
    kind: "words",
    items: [
    { word: "farm", emoji: "🚜", line: "WORK ON THE FARM!" },
    { word: "tractor", emoji: "🚜", line: "VROOM TRACTOR!" },
    { word: "barn", emoji: "🏚️", line: "RED BARN!" },
    { word: "hay", emoji: "🌾", line: "DRY HAY!" },
    ],
  },
  dinosaurs: {
    label: "DINOS",
    icon: "🦕",
    kind: "words",
    items: [
    { word: "dinosaur", emoji: "🦕", line: "BIG DINOSAUR!" },
    { word: "t-rex", emoji: "🦖", line: "T-REX HAS BIG TEETH!" },
    { word: "egg", emoji: "🥚", line: "DINO EGG!" },
    ],
  },
  insects: {
    label: "BUGS",
    icon: "🐛",
    kind: "words",
    items: [
    { word: "bug", emoji: "🐛", line: "TINY BUG!" },
    { word: "bee", emoji: "🐝", line: "THE BEE BUZZES!" },
    { word: "butterfly", emoji: "🦋", line: "THE BUTTERFLY IS COLORFUL!" },
    { word: "ladybug", emoji: "🐞", line: "THE LADYBUG HAS SPOTS!" },
    { word: "ant", emoji: "🐜", line: "THE ANT IS SMALL!" },
    { word: "snail", emoji: "🐌", line: "THE SNAIL IS SLOW!" },
    ],
  },
  birds: {
    label: "BIRDS",
    icon: "🐦",
    kind: "words",
    items: [
    { word: "chick", emoji: "🐤", line: "YELLOW CHICK!" },
    { word: "duck", emoji: "🦆", line: "QUACK QUACK!" },
    { word: "owl", emoji: "🦉", line: "THE OWL SAYS WHO!" },
    { word: "nest", emoji: "🪺", line: "BIRDS IN A NEST!" },
    ],
  },
  food: {
    label: "FOOD",
    icon: "🍎",
    kind: "words",
    items: [
    { word: "apple", emoji: "🍎", line: "CRUNCHY APPLE!" },
    { word: "banana", emoji: "🍌", line: "YELLOW BANANA!" },
    { word: "orange", emoji: "🍊", line: "JUICY ORANGE!" },
    { word: "grape", emoji: "🍇", line: "SWEET GRAPES!" },
    { word: "strawberry", emoji: "🍓", line: "RED STRAWBERRY!" },
    { word: "watermelon", emoji: "🍉", line: "BIG WATERMELON!" },
    { word: "peach", emoji: "🍑", line: "SOFT PEACH!" },
    { word: "cherry", emoji: "🍒", line: "TINY CHERRIES!" },
    { word: "lemon", emoji: "🍋", line: "SOUR LEMON!" },
    { word: "carrot", emoji: "🥕", line: "ORANGE CARROT!" },
    { word: "broccoli", emoji: "🥦", line: "GREEN BROCCOLI!" },
    { word: "corn", emoji: "🌽", line: "YELLOW CORN!" },
    { word: "potato", emoji: "🥔", line: "BROWN POTATO!" },
    { word: "tomato", emoji: "🍅", line: "RED TOMATO!" },
    { word: "cucumber", emoji: "🥒", line: "COOL CUCUMBER!" },
    { word: "mushroom", emoji: "🍄", line: "FUNNY MUSHROOM!" },
    { word: "bread", emoji: "🍞", line: "WARM BREAD!" },
    { word: "cheese", emoji: "🧀", line: "YUMMY CHEESE!" },
    { word: "egg", emoji: "🥚", line: "WHITE EGG!" },
    { word: "milk", emoji: "🥛", line: "COLD MILK!" },
    { word: "pizza", emoji: "🍕", line: "HOT PIZZA!" },
    { word: "burger", emoji: "🍔", line: "BIG BURGER!" },
    { word: "hot dog", emoji: "🌭", line: "HOT DOG!" },
    { word: "sandwich", emoji: "🥪", line: "TASTY SANDWICH!" },
    { word: "soup", emoji: "🍲", line: "WARM SOUP!" },
    { word: "rice", emoji: "🍚", line: "WHITE RICE!" },
    { word: "cookie", emoji: "🍪", line: "SWEET COOKIE!" },
    { word: "cake", emoji: "🎂", line: "HAPPY BIRTHDAY CAKE!" },
    { word: "donut", emoji: "🍩", line: "PINK DONUT!" },
    { word: "ice cream", emoji: "🍦", line: "COLD ICE CREAM!" },
    { word: "candy", emoji: "🍬", line: "SWEET CANDY!" },
    { word: "chocolate", emoji: "🍫", line: "CHOCOLATE BAR!" },
    { word: "honey", emoji: "🍯", line: "STICKY HONEY!" },
    { word: "popcorn", emoji: "🍿", line: "POP POP POPCORN!" },
    { word: "juice", emoji: "🧃", line: "FRUIT JUICE!" },
    { word: "water", emoji: "💧", line: "DRINK WATER!" },
    { word: "pineapple", emoji: "🍍", line: "SPIKY PINEAPPLE!" },
    { word: "kiwi", emoji: "🥝", line: "FUZZY KIWI!" },
    { word: "pear", emoji: "🍐", line: "GREEN PEAR!" },
    ],
  },
  colors: {
    label: "COLORS",
    icon: "🎨",
    kind: "words",
    items: [
    { word: "red", emoji: "🔴", line: "RED LIKE AN APPLE!" },
    { word: "blue", emoji: "🔵", line: "BLUE LIKE THE SKY!" },
    { word: "green", emoji: "🟢", line: "GREEN LIKE GRASS!" },
    { word: "yellow", emoji: "🟡", line: "YELLOW LIKE THE SUN!" },
    { word: "orange", emoji: "🟠", line: "ORANGE LIKE A CARROT!" },
    { word: "purple", emoji: "🟣", line: "PURPLE LIKE GRAPES!" },
    { word: "pink", emoji: "🩷", line: "PRETTY PINK!" },
    { word: "black", emoji: "⚫", line: "BLACK LIKE NIGHT!" },
    { word: "white", emoji: "⚪", line: "WHITE LIKE SNOW!" },
    { word: "brown", emoji: "🟤", line: "BROWN LIKE CHOCOLATE!" },
    { word: "gray", emoji: "⬜", line: "GRAY LIKE A CLOUD!" },
    { word: "gold", emoji: "🥇", line: "SHINY GOLD!" },
    { word: "silver", emoji: "🥈", line: "COOL SILVER!" },
    ],
  },
  family: {
    label: "FAMILY",
    icon: "👨‍👩‍👧",
    kind: "words",
    items: [
    { word: "pet", emoji: "🐾", line: "WE LOVE OUR PET!" },
    { word: "team", emoji: "👥", line: "WE ARE A TEAM!" },
    ],
  },
  body: {
    label: "BODY",
    icon: "🧒",
    kind: "words",
    items: [
    { word: "head", emoji: "🙂", line: "YOUR HEAD THINKS!" },
    { word: "eye", emoji: "👁️", line: "YOU SEE WITH YOUR EYES!" },
    { word: "ear", emoji: "👂", line: "YOU HEAR WITH YOUR EARS!" },
    { word: "nose", emoji: "👃", line: "YOU SMELL WITH YOUR NOSE!" },
    { word: "mouth", emoji: "👄", line: "YOU TALK WITH YOUR MOUTH!" },
    { word: "tooth", emoji: "🦷", line: "BRUSH YOUR TEETH!" },
    { word: "hand", emoji: "✋", line: "WAVE YOUR HAND!" },
    { word: "finger", emoji: "☝️", line: "COUNT ON YOUR FINGERS!" },
    { word: "arm", emoji: "💪", line: "STRONG ARMS!" },
    { word: "leg", emoji: "🦵", line: "LEGS HELP YOU RUN!" },
    { word: "foot", emoji: "🦶", line: "STOMP YOUR FOOT!" },
    { word: "toe", emoji: "👣", line: "WIGGLE YOUR TOES!" },
    { word: "knee", emoji: "🦵", line: "BEND YOUR KNEES!" },
    { word: "hair", emoji: "💇", line: "COMB YOUR HAIR!" },
    { word: "heart", emoji: "❤️", line: "YOUR HEART GOES THUMP!" },
    { word: "face", emoji: "😊", line: "HAPPY FACE!" },
    { word: "neck", emoji: "🧣", line: "TURN YOUR NECK!" },
    { word: "back", emoji: "🎒", line: "STRAIGHT BACK!" },
    ],
  },
  clothes: {
    label: "CLOTHES",
    icon: "👕",
    kind: "words",
    items: [
    { word: "hat", emoji: "🧢", line: "WEAR A HAT!" },
    { word: "shirt", emoji: "👕", line: "A COMFY SHIRT!" },
    { word: "pants", emoji: "👖", line: "BLUE JEANS!" },
    { word: "dress", emoji: "👗", line: "A PRETTY DRESS!" },
    { word: "sock", emoji: "🧦", line: "WARM SOCKS!" },
    { word: "shoe", emoji: "👟", line: "TIE YOUR SHOES!" },
    { word: "boot", emoji: "🥾", line: "BIG BOOTS!" },
    { word: "coat", emoji: "🧥", line: "WARM COAT!" },
    { word: "scarf", emoji: "🧣", line: "COZY SCARF!" },
    { word: "glove", emoji: "🧤", line: "WINTER GLOVES!" },
    { word: "glasses", emoji: "👓", line: "I CAN SEE!" },
    { word: "t-shirt", emoji: "👕", line: "COMFY T-SHIRT!" },
    { word: "shorts", emoji: "🩳", line: "SUMMER SHORTS!" },
    ],
  },
  jobs: {
    label: "JOBS",
    icon: "👷",
    kind: "words",
    items: [
    { word: "doctor", emoji: "👩‍⚕️", line: "DOCTORS HELP PEOPLE!" },
    { word: "teacher", emoji: "👩‍🏫", line: "TEACHERS HELP US LEARN!" },
    { word: "firefighter", emoji: "👨‍🚒", line: "FIREFIGHTERS ARE BRAVE!" },
    { word: "vet", emoji: "🐾", line: "VETS HELP ANIMALS!" },
    ],
  },
  home: {
    label: "HOME",
    icon: "🏠",
    kind: "words",
    items: [
    { word: "house", emoji: "🏠", line: "THIS IS MY HOUSE!" },
    { word: "bed", emoji: "🛏️", line: "SLEEP IN YOUR BED!" },
    { word: "chair", emoji: "🪑", line: "SIT ON THE CHAIR!" },
    { word: "table", emoji: "🪑", line: "EAT AT THE TABLE!" },
    { word: "door", emoji: "🚪", line: "OPEN THE DOOR!" },
    { word: "window", emoji: "🪟", line: "LOOK OUT THE WINDOW!" },
    { word: "lamp", emoji: "💡", line: "TURN ON THE LAMP!" },
    { word: "book", emoji: "📚", line: "READ A BOOK!" },
    { word: "toy", emoji: "🧸", line: "PLAY WITH TOYS!" },
    { word: "ball", emoji: "⚽", line: "KICK THE BALL!" },
    { word: "cup", emoji: "☕", line: "A LITTLE CUP!" },
    { word: "spoon", emoji: "🥄", line: "EAT WITH A SPOON!" },
    { word: "fork", emoji: "🍴", line: "EAT WITH A FORK!" },
    { word: "plate", emoji: "🍽️", line: "FOOD ON A PLATE!" },
    { word: "box", emoji: "📦", line: "WHAT IS IN THE BOX?" },
    { word: "pillow", emoji: "🛏️", line: "SOFT PILLOW!" },
    { word: "soap", emoji: "🧼", line: "WASH WITH SOAP!" },
    { word: "towel", emoji: "🧺", line: "DRY WITH A TOWEL!" },
    { word: "brush", emoji: "🪮", line: "BRUSH YOUR HAIR!" },
    ],
  },
  school: {
    label: "SCHOOL",
    icon: "🏫",
    kind: "words",
    items: [
    { word: "school", emoji: "🏫", line: "I GO TO SCHOOL!" },
    { word: "teacher", emoji: "👩‍🏫", line: "THE TEACHER HELPS US!" },
    { word: "student", emoji: "🧑‍🎓", line: "I AM A STUDENT!" },
    { word: "pencil", emoji: "✏️", line: "WRITE WITH A PENCIL!" },
    { word: "pen", emoji: "🖊️", line: "WRITE WITH A PEN!" },
    { word: "paper", emoji: "📄", line: "DRAW ON PAPER!" },
    { word: "desk", emoji: "🪑", line: "SIT AT YOUR DESK!" },
    { word: "bag", emoji: "🎒", line: "MY SCHOOL BAG!" },
    { word: "ruler", emoji: "📏", line: "MEASURE WITH A RULER!" },
    { word: "crayon", emoji: "🖍️", line: "COLOR WITH CRAYONS!" },
    { word: "map", emoji: "🗺️", line: "LOOK AT THE MAP!" },
    ],
  },
  toys: {
    label: "TOYS",
    icon: "🧸",
    kind: "words",
    items: [
    { word: "doll", emoji: "🪆", line: "CUDDLE THE DOLL!" },
    { word: "teddy", emoji: "🧸", line: "TEDDY BEAR HUG!" },
    { word: "blocks", emoji: "🧱", line: "STACK THE BLOCKS!" },
    { word: "puzzle", emoji: "🧩", line: "FIT THE PUZZLE!" },
    { word: "kite", emoji: "🪁", line: "FLY A KITE!" },
    { word: "balloon", emoji: "🎈", line: "POP THE BALLOON!" },
    { word: "drum", emoji: "🥁", line: "BANG THE DRUM!" },
    { word: "guitar", emoji: "🎸", line: "STRUM THE GUITAR!" },
    { word: "piano", emoji: "🎹", line: "PLAY THE PIANO!" },
    { word: "robot", emoji: "🤖", line: "BEEP BOOP ROBOT!" },
    { word: "slide", emoji: "🛝", line: "WHEEE DOWN THE SLIDE!" },
    { word: "swing", emoji: "🪢", line: "SWING HIGH!" },
    { word: "yo-yo", emoji: "🪀", line: "SPIN THE YO-YO!" },
    { word: "sandbox", emoji: "🏖️", line: "DIG IN THE SAND!" },
    { word: "bubbles", emoji: "🫧", line: "POP THE BUBBLES!" },
    ],
  },
  nature: {
    label: "NATURE",
    icon: "🌳",
    kind: "words",
    items: [
    { word: "sun", emoji: "☀️", line: "THE SUN IS BRIGHT!" },
    { word: "moon", emoji: "🌙", line: "THE MOON AT NIGHT!" },
    { word: "star", emoji: "⭐", line: "TWINKLE TWINKLE STAR!" },
    { word: "cloud", emoji: "☁️", line: "FLUFFY CLOUD!" },
    { word: "rain", emoji: "🌧️", line: "PITTER PATTER RAIN!" },
    { word: "snow", emoji: "❄️", line: "COLD WHITE SNOW!" },
    { word: "wind", emoji: "💨", line: "WHOOSH GOES THE WIND!" },
    { word: "tree", emoji: "🌳", line: "TALL GREEN TREE!" },
    { word: "flower", emoji: "🌸", line: "PRETTY FLOWER!" },
    { word: "grass", emoji: "🌿", line: "SOFT GREEN GRASS!" },
    { word: "rock", emoji: "🪨", line: "HARD ROCK!" },
    { word: "river", emoji: "🏞️", line: "THE RIVER FLOWS!" },
    { word: "sea", emoji: "🌊", line: "BIG BLUE SEA!" },
    { word: "beach", emoji: "🏖️", line: "SANDY BEACH!" },
    { word: "mountain", emoji: "⛰️", line: "TALL MOUNTAIN!" },
    { word: "forest", emoji: "🌲", line: "TREES IN THE FOREST!" },
    { word: "leaf", emoji: "🍃", line: "A GREEN LEAF!" },
    { word: "rainbow", emoji: "🌈", line: "COLORS IN THE SKY!" },
    ],
  },
  weather: {
    label: "WEATHER",
    icon: "🌤️",
    kind: "words",
    items: [
    { word: "sunny", emoji: "☀️", line: "IT IS SUNNY TODAY!" },
    { word: "cloudy", emoji: "☁️", line: "IT IS CLOUDY!" },
    { word: "rainy", emoji: "🌧️", line: "IT IS RAINY!" },
    { word: "snowy", emoji: "🌨️", line: "IT IS SNOWY!" },
    { word: "windy", emoji: "💨", line: "IT IS WINDY!" },
    { word: "storm", emoji: "⛈️", line: "BIG STORM!" },
    { word: "hot", emoji: "🥵", line: "IT IS HOT!" },
    { word: "cold", emoji: "🥶", line: "IT IS COLD!" },
    { word: "warm", emoji: "🌡️", line: "NICE AND WARM!" },
    { word: "cool", emoji: "🧊", line: "NICE AND COOL!" },
    ],
  },
  seasons: {
    label: "SEASONS",
    icon: "🍂",
    kind: "words",
    items: [
    { word: "spring", emoji: "🌸", line: "FLOWERS IN SPRING!" },
    { word: "summer", emoji: "☀️", line: "HOT SUMMER SUN!" },
    { word: "winter", emoji: "❄️", line: "SNOW IN WINTER!" },
    { word: "snowman", emoji: "⛄", line: "BUILD A SNOWMAN!" },
    ],
  },
  places: {
    label: "PLACES",
    icon: "🗺️",
    kind: "words",
    items: [
    { word: "park", emoji: "🏞️", line: "PLAY IN THE PARK!" },
    { word: "zoo", emoji: "🦁", line: "ANIMALS AT THE ZOO!" },
    { word: "farm", emoji: "🚜", line: "ANIMALS ON THE FARM!" },
    { word: "hospital", emoji: "🏥", line: "DOCTORS AT THE HOSPITAL!" },
    { word: "playground", emoji: "🛝", line: "FUN AT THE PLAYGROUND!" },
    { word: "beach", emoji: "🏖️", line: "SAND AND WAVES!" },
    { word: "museum", emoji: "🏛️", line: "LOOK AT THE MUSEUM!" },
    { word: "bakery", emoji: "🥐", line: "SMELL THE BAKERY!" },
    { word: "pool", emoji: "🏊", line: "SWIM IN THE POOL!" },
    { word: "castle", emoji: "🏰", line: "OLD CASTLE!" },
    ],
  },
  transport: {
    label: "CARS",
    icon: "🚗",
    kind: "words",
    items: [
    { word: "car", emoji: "🚗", line: "BEEP BEEP CAR!" },
    { word: "bus", emoji: "🚌", line: "THE BUS IS BIG!" },
    { word: "train", emoji: "🚆", line: "CHOO CHOO TRAIN!" },
    { word: "plane", emoji: "✈️", line: "THE PLANE FLIES HIGH!" },
    { word: "boat", emoji: "⛵", line: "SAIL THE BOAT!" },
    { word: "bike", emoji: "🚲", line: "PEDAL YOUR BIKE!" },
    { word: "truck", emoji: "🚚", line: "THE TRUCK CARRIES STUFF!" },
    { word: "taxi", emoji: "🚕", line: "YELLOW TAXI!" },
    { word: "helicopter", emoji: "🚁", line: "THE HELICOPTER SPINS!" },
    { word: "rocket", emoji: "🚀", line: "BLAST OFF!" },
    { word: "ship", emoji: "🚢", line: "BIG SHIP ON THE SEA!" },
    { word: "ambulance", emoji: "🚑", line: "NEE NAW AMBULANCE!" },
    { word: "fire truck", emoji: "🚒", line: "FIRE TRUCK SAVES THE DAY!" },
    { word: "police car", emoji: "🚓", line: "POLICE CAR!" },
    { word: "road", emoji: "🛣️", line: "CAR ON THE ROAD!" },
    { word: "bridge", emoji: "🌉", line: "CROSS THE BRIDGE!" },
    ],
  },
  sports: {
    label: "SPORTS",
    icon: "⚽",
    kind: "words",
    items: [
    { word: "soccer", emoji: "⚽", line: "KICK THE SOCCER BALL!" },
    { word: "basketball", emoji: "🏀", line: "BOUNCE BASKETBALL!" },
    { word: "tennis", emoji: "🎾", line: "HIT THE TENNIS BALL!" },
    { word: "baseball", emoji: "⚾", line: "THROW BASEBALL!" },
    { word: "swimming", emoji: "🏊", line: "SWIM IN THE POOL!" },
    { word: "skating", emoji: "⛸️", line: "GLIDE ON ICE!" },
    { word: "skiing", emoji: "⛷️", line: "SKI DOWN THE HILL!" },
    { word: "running", emoji: "🏃", line: "RUN A RACE!" },
    { word: "cycling", emoji: "🚴", line: "RIDE YOUR BIKE!" },
    ],
  },
  actions: {
    label: "ACTIONS",
    icon: "🏃",
    kind: "words",
    items: [
    { word: "run", emoji: "🏃", line: "RUN FAST!" },
    { word: "walk", emoji: "🚶", line: "WALK SLOWLY!" },
    { word: "jump", emoji: "🦘", line: "JUMP UP HIGH!" },
    { word: "sit", emoji: "🪑", line: "SIT DOWN!" },
    { word: "stand", emoji: "🧍", line: "STAND UP TALL!" },
    { word: "sleep", emoji: "😴", line: "GO TO SLEEP!" },
    { word: "eat", emoji: "🍽️", line: "EAT YOUR FOOD!" },
    { word: "drink", emoji: "🥤", line: "DRINK WATER!" },
    { word: "play", emoji: "🎮", line: "LET US PLAY!" },
    { word: "read", emoji: "📖", line: "READ A STORY!" },
    { word: "draw", emoji: "🎨", line: "DRAW A PICTURE!" },
    { word: "sing", emoji: "🎤", line: "SING A SONG!" },
    { word: "swim", emoji: "🏊", line: "SWIM IN THE POOL!" },
    { word: "climb", emoji: "🧗", line: "CLIMB UP!" },
    { word: "throw", emoji: "🤾", line: "THROW THE BALL!" },
    { word: "catch", emoji: "🤲", line: "CATCH IT!" },
    { word: "kick", emoji: "⚽", line: "KICK THE BALL!" },
    { word: "wash", emoji: "🧼", line: "WASH YOUR HANDS!" },
    { word: "brush", emoji: "🪥", line: "BRUSH YOUR TEETH!" },
    { word: "hug", emoji: "🤗", line: "GIVE A HUG!" },
    { word: "kiss", emoji: "😘", line: "KISS ON THE CHEEK!" },
    { word: "share", emoji: "🎁", line: "SHARE WITH FRIENDS!" },
    { word: "listen", emoji: "👂", line: "LISTEN CAREFULLY!" },
    { word: "look", emoji: "👀", line: "LOOK AROUND!" },
    { word: "think", emoji: "🤔", line: "THINK HARD!" },
    { word: "build", emoji: "🧱", line: "BUILD SOMETHING!" },
    { word: "hide", emoji: "🙈", line: "HIDE AND SEEK!" },
    { word: "find", emoji: "🔍", line: "FIND IT!" },
    ],
  },
  shapes: {
    label: "SHAPES",
    icon: "⬛",
    kind: "words",
    items: [
    { word: "circle", emoji: "⭕", line: "A ROUND CIRCLE!" },
    { word: "square", emoji: "⬛", line: "FOUR SIDES ON A SQUARE!" },
    { word: "triangle", emoji: "🔺", line: "A TRIANGLE HAS THREE CORNERS!" },
    { word: "heart", emoji: "❤️", line: "A HEART SHAPE!" },
    ],
  },
  time: {
    label: "TIME",
    icon: "🕐",
    kind: "words",
    items: [
    { word: "day", emoji: "🌞", line: "THE DAY IS BRIGHT!" },
    { word: "night", emoji: "🌙", line: "GOOD NIGHT!" },
    { word: "morning", emoji: "🌅", line: "GOOD MORNING!" },
    { word: "today", emoji: "📅", line: "TODAY IS FUN!" },
    { word: "tomorrow", emoji: "⏭️", line: "SEE YOU TOMORROW!" },
    { word: "birthday", emoji: "🎂", line: "HAPPY BIRTHDAY!" },
    ],
  },
  music: {
    label: "MUSIC",
    icon: "🎵",
    kind: "words",
    items: [
    { word: "song", emoji: "🎶", line: "SING A SONG!" },
    { word: "drum", emoji: "🥁", line: "BANG THE DRUM!" },
    { word: "piano", emoji: "🎹", line: "PLAY PIANO KEYS!" },
    { word: "guitar", emoji: "🎸", line: "STRUM THE GUITAR!" },
    { word: "violin", emoji: "🎻", line: "SWEET VIOLIN!" },
    ],
  },
  fantasy: {
    label: "MAGIC",
    icon: "🦄",
    kind: "words",
    items: [
    { word: "unicorn", emoji: "🦄", line: "SPARKLY UNICORN!" },
    { word: "dragon", emoji: "🐉", line: "BIG DRAGON!" },
    { word: "fairy", emoji: "🧚", line: "TINY FAIRY!" },
    { word: "princess", emoji: "👸", line: "BRAVE PRINCESS!" },
    { word: "castle", emoji: "🏰", line: "TALL CASTLE!" },
    ],
  },
  space: {
    label: "SPACE",
    icon: "🚀",
    kind: "words",
    items: [
    { word: "earth", emoji: "🌍", line: "OUR PLANET EARTH!" },
    { word: "moon", emoji: "🌙", line: "MOON IN THE SKY!" },
    { word: "sun", emoji: "☀️", line: "BIG HOT SUN!" },
    { word: "star", emoji: "⭐", line: "TWINKLE STAR!" },
    { word: "rocket", emoji: "🚀", line: "BLAST OFF ROCKET!" },
    ],
  },
};
