/* global LESSONS — vocabulary for Langy (100% client-side) */
const LETTER_ITEMS = [
  ["A", "🍎", "A IS FOR APPLE"],
  ["B", "🐻", "B IS FOR BEAR"],
  ["C", "🐱", "C IS FOR CAT"],
  ["D", "🐶", "D IS FOR DOG"],
  ["E", "🐘", "E IS FOR ELEPHANT"],
  ["F", "🐟", "F IS FOR FISH"],
  ["G", "🍇", "G IS FOR GRAPES"],
  ["H", "🏠", "H IS FOR HOUSE"],
  ["I", "🧊", "I IS FOR ICE"],
  ["J", "🧃", "J IS FOR JUICE"],
  ["K", "🪁", "K IS FOR KITE"],
  ["L", "🦁", "L IS FOR LION"],
  ["M", "🌙", "M IS FOR MOON"],
  ["N", "🪺", "N IS FOR NEST"],
  ["O", "🍊", "O IS FOR ORANGE"],
  ["P", "🐷", "P IS FOR PIG"],
  ["Q", "👑", "Q IS FOR QUEEN"],
  ["R", "🐰", "R IS FOR RABBIT"],
  ["S", "☀️", "S IS FOR SUN"],
  ["T", "🌳", "T IS FOR TREE"],
  ["U", "☂️", "U IS FOR UMBRELLA"],
  ["V", "🎻", "V IS FOR VIOLIN"],
  ["W", "💧", "W IS FOR WATER"],
  ["X", "🩻", "X IS FOR X-RAY"],
  ["Y", "🪀", "Y IS FOR YO-YO"],
  ["Z", "🦓", "Z IS FOR ZEBRA"],
].map(([letter, emoji, line]) => ({
  word: letter.toLowerCase(),
  letter,
  emoji,
  line,
}));

const DIGIT_ITEMS = [
  ["0", "ZERO", "0️⃣", "ZERO EGGS IN THE BOX!"],
  ["1", "ONE", "1️⃣", "ONE LITTLE STAR!"],
  ["2", "TWO", "2️⃣", "TWO HANDS!"],
  ["3", "THREE", "3️⃣", "THREE BEARS!"],
  ["4", "FOUR", "4️⃣", "FOUR WHEELS!"],
  ["5", "FIVE", "5️⃣", "HIGH FIVE!"],
  ["6", "SIX", "6️⃣", "SIX EGGS!"],
  ["7", "SEVEN", "7️⃣", "SEVEN COLORS!"],
  ["8", "EIGHT", "8️⃣", "EIGHT LEGS ON A SPIDER!"],
  ["9", "NINE", "9️⃣", "NINE BALLOONS!"],
  ["10", "TEN", "🔟", "TEN FINGERS!"],
  ["11", "ELEVEN", "🔢", "ELEVEN STEPS UP!"],
  ["12", "TWELVE", "🔢", "TWELVE MONTHS IN A YEAR!"],
  ["20", "TWENTY", "🔢", "TWENTY TOES IF YOU COUNT FRIENDS!"],
  ["100", "HUNDRED", "💯", "ONE HUNDRED IS A BIG NUMBER!"],
].map(([digit, word, emoji, line]) => ({
  word: word.toLowerCase(),
  digit,
  emoji,
  line,
}));

function pack(rows) {
  return rows.map(([word, emoji, line]) => ({
    word: word.toLowerCase(),
    emoji,
    line,
  }));
}

const LESSONS = {
  letters: {
    label: "LETTERS",
    icon: "🔤",
    kind: "letters",
    items: LETTER_ITEMS,
  },
  digits: {
    label: "DIGITS",
    icon: "🔢",
    kind: "digits",
    items: DIGIT_ITEMS,
  },
  numbers: {
    label: "NUMBERS",
    icon: "🧮",
    kind: "words",
    items: DIGIT_ITEMS.filter((d) => !["0", "100"].includes(d.digit)),
  },
  animals: {
    label: "ANIMALS",
    icon: "🐾",
    kind: "words",
    items: pack([
      ["cat", "🐱", "THE CAT SAYS MEOW!"],
      ["dog", "🐶", "THE DOG SAYS WOOF!"],
      ["bird", "🐦", "THE BIRD CAN FLY!"],
      ["fish", "🐟", "THE FISH SWIMS!"],
      ["cow", "🐮", "THE COW SAYS MOO!"],
      ["pig", "🐷", "THE PIG SAYS OINK!"],
      ["duck", "🦆", "THE DUCK SAYS QUACK!"],
      ["frog", "🐸", "THE FROG SAYS RIBBIT!"],
      ["lion", "🦁", "THE LION ROARS!"],
      ["tiger", "🐯", "THE TIGER HAS STRIPES!"],
      ["bear", "🐻", "THE BEAR IS BIG AND FUZZY!"],
      ["horse", "🐴", "THE HORSE RUNS FAST!"],
      ["sheep", "🐑", "THE SHEEP SAYS BAA!"],
      ["goat", "🐐", "THE GOAT CLIMBS ROCKS!"],
      ["chicken", "🐔", "THE CHICKEN SAYS CLUCK!"],
      ["rabbit", "🐰", "THE RABBIT HOPS!"],
      ["mouse", "🐭", "THE MOUSE IS SMALL!"],
      ["elephant", "🐘", "THE ELEPHANT IS HUGE!"],
      ["giraffe", "🦒", "THE GIRAFFE HAS A LONG NECK!"],
      ["zebra", "🦓", "THE ZEBRA HAS STRIPES!"],
      ["monkey", "🐵", "THE MONKEY SWINGS!"],
      ["panda", "🐼", "THE PANDA LOVES BAMBOO!"],
      ["koala", "🐨", "THE KOALA SLEEPS IN TREES!"],
      ["owl", "🦉", "THE OWL SAYS WHO!"],
      ["bee", "🐝", "THE BEE BUZZES!"],
      ["butterfly", "🦋", "THE BUTTERFLY IS COLORFUL!"],
      ["snake", "🐍", "THE SNAKE SLITHERS!"],
      ["turtle", "🐢", "THE TURTLE IS SLOW!"],
      ["whale", "🐋", "THE WHALE IS ENORMOUS!"],
      ["dolphin", "🐬", "THE DOLPHIN JUMPS!"],
      ["shark", "🦈", "THE SHARK SWIMS IN THE SEA!"],
      ["crab", "🦀", "THE CRAB WALKS SIDEWAYS!"],
      ["penguin", "🐧", "THE PENGUIN LOVES ICE!"],
      ["fox", "🦊", "THE FOX IS CLEVER!"],
      ["wolf", "🐺", "THE WOLF HOWLS!"],
      ["deer", "🦌", "THE DEER RUNS IN THE FOREST!"],
      ["squirrel", "🐿️", "THE SQUIRREL LOVES NUTS!"],
      ["bat", "🦇", "THE BAT FLIES AT NIGHT!"],
      ["snail", "🐌", "THE SNAIL CARRIES A SHELL!"],
      ["octopus", "🐙", "THE OCTOPUS HAS EIGHT ARMS!"],
      ["hippo", "🦛", "THE HIPPO LOVES WATER!"],
      ["rhino", "🦏", "THE RHINO HAS A BIG HORN!"],
      ["camel", "🐫", "THE CAMEL LIVES IN THE DESERT!"],
      ["kangaroo", "🦘", "THE KANGAROO JUMPS HIGH!"],
      ["parrot", "🦜", "THE PARROT CAN TALK!"],
      ["eagle", "🦅", "THE EAGLE FLIES HIGH!"],
      ["ant", "🐜", "THE ANT IS TINY BUT STRONG!"],
      ["ladybug", "🐞", "THE LADYBUG HAS SPOTS!"],
    ]),
  },
  colors: {
    label: "COLORS",
    icon: "🎨",
    kind: "words",
    items: pack([
      ["red", "🔴", "RED LIKE AN APPLE!"],
      ["blue", "🔵", "BLUE LIKE THE SKY!"],
      ["green", "🟢", "GREEN LIKE GRASS!"],
      ["yellow", "🟡", "YELLOW LIKE THE SUN!"],
      ["orange", "🟠", "ORANGE LIKE A CARROT!"],
      ["purple", "🟣", "PURPLE LIKE GRAPES!"],
      ["pink", "🩷", "PRETTY PINK!"],
      ["black", "⚫", "BLACK LIKE NIGHT!"],
      ["white", "⚪", "WHITE LIKE SNOW!"],
      ["brown", "🟤", "BROWN LIKE CHOCOLATE!"],
      ["gray", "⬜", "GRAY LIKE A CLOUD!"],
      ["gold", "🥇", "SHINY GOLD!"],
      ["silver", "🥈", "COOL SILVER!"],
    ]),
  },
  food: {
    label: "FOOD",
    icon: "🍎",
    kind: "words",
    items: pack([
      ["apple", "🍎", "CRUNCHY APPLE!"],
      ["banana", "🍌", "YELLOW BANANA!"],
      ["orange", "🍊", "JUICY ORANGE!"],
      ["grape", "🍇", "SWEET GRAPES!"],
      ["strawberry", "🍓", "RED STRAWBERRY!"],
      ["watermelon", "🍉", "BIG WATERMELON!"],
      ["peach", "🍑", "SOFT PEACH!"],
      ["cherry", "🍒", "TINY CHERRIES!"],
      ["lemon", "🍋", "SOUR LEMON!"],
      ["carrot", "🥕", "ORANGE CARROT!"],
      ["broccoli", "🥦", "GREEN BROCCOLI!"],
      ["corn", "🌽", "YELLOW CORN!"],
      ["potato", "🥔", "BROWN POTATO!"],
      ["tomato", "🍅", "RED TOMATO!"],
      ["cucumber", "🥒", "COOL CUCUMBER!"],
      ["mushroom", "🍄", "FUNNY MUSHROOM!"],
      ["bread", "🍞", "WARM BREAD!"],
      ["cheese", "🧀", "YUMMY CHEESE!"],
      ["egg", "🥚", "WHITE EGG!"],
      ["milk", "🥛", "COLD MILK!"],
      ["pizza", "🍕", "HOT PIZZA!"],
      ["burger", "🍔", "BIG BURGER!"],
      ["hot dog", "🌭", "HOT DOG!"],
      ["sandwich", "🥪", "TASTY SANDWICH!"],
      ["soup", "🍲", "WARM SOUP!"],
      ["rice", "🍚", "WHITE RICE!"],
      ["cookie", "🍪", "SWEET COOKIE!"],
      ["cake", "🎂", "HAPPY BIRTHDAY CAKE!"],
      ["donut", "🍩", "PINK DONUT!"],
      ["ice cream", "🍦", "COLD ICE CREAM!"],
      ["candy", "🍬", "SWEET CANDY!"],
      ["chocolate", "🍫", "CHOCOLATE BAR!"],
      ["honey", "🍯", "STICKY HONEY!"],
      ["popcorn", "🍿", "POP POP POPCORN!"],
      ["juice", "🧃", "FRUIT JUICE!"],
      ["water", "💧", "DRINK WATER!"],
    ]),
  },
  body: {
    label: "BODY",
    icon: "🧒",
    kind: "words",
    items: pack([
      ["head", "🙂", "YOUR HEAD THINKS!"],
      ["eye", "👁️", "YOU SEE WITH YOUR EYES!"],
      ["ear", "👂", "YOU HEAR WITH YOUR EARS!"],
      ["nose", "👃", "YOU SMELL WITH YOUR NOSE!"],
      ["mouth", "👄", "YOU TALK WITH YOUR MOUTH!"],
      ["tooth", "🦷", "BRUSH YOUR TEETH!"],
      ["hand", "✋", "WAVE YOUR HAND!"],
      ["finger", "☝️", "COUNT ON YOUR FINGERS!"],
      ["arm", "💪", "STRONG ARMS!"],
      ["leg", "🦵", "LEGS HELP YOU RUN!"],
      ["foot", "🦶", "STOMP YOUR FOOT!"],
      ["toe", "👣", "WIGGLE YOUR TOES!"],
      ["knee", "🦵", "BEND YOUR KNEES!"],
      ["hair", "💇", "COMB YOUR HAIR!"],
      ["heart", "❤️", "YOUR HEART GOES THUMP!"],
      ["bone", "🦴", "BONES HOLD YOU UP!"],
    ]),
  },
  family: {
    label: "FAMILY",
    icon: "👨‍👩‍👧",
    kind: "words",
    items: pack([
      ["mom", "👩", "I LOVE MY MOM!"],
      ["dad", "👨", "I LOVE MY DAD!"],
      ["baby", "👶", "THE BABY IS SMALL!"],
      ["sister", "👧", "MY SISTER PLAYS WITH ME!"],
      ["brother", "👦", "MY BROTHER PLAYS WITH ME!"],
      ["grandma", "👵", "GRANDMA GIVES HUGS!"],
      ["grandpa", "👴", "GRANDPA TELLS STORIES!"],
      ["family", "👨‍👩‍👧‍👦", "WE ARE A FAMILY!"],
      ["friend", "🧑‍🤝‍🧑", "A GOOD FRIEND IS KIND!"],
    ]),
  },
  clothes: {
    label: "CLOTHES",
    icon: "👕",
    kind: "words",
    items: pack([
      ["hat", "🧢", "WEAR A HAT!"],
      ["shirt", "👕", "A COMFY SHIRT!"],
      ["pants", "👖", "BLUE JEANS!"],
      ["dress", "👗", "A PRETTY DRESS!"],
      ["sock", "🧦", "WARM SOCKS!"],
      ["shoe", "👟", "TIE YOUR SHOES!"],
      ["boot", "🥾", "BIG BOOTS!"],
      ["coat", "🧥", "WARM COAT!"],
      ["scarf", "🧣", "COZY SCARF!"],
      ["glove", "🧤", "WINTER GLOVES!"],
      ["pajamas", "🛏️", "SLEEP IN PAJAMAS!"],
      ["glasses", "👓", "I CAN SEE!"],
    ]),
  },
  home: {
    label: "HOME",
    icon: "🏠",
    kind: "words",
    items: pack([
      ["house", "🏠", "THIS IS MY HOUSE!"],
      ["bed", "🛏️", "SLEEP IN YOUR BED!"],
      ["chair", "🪑", "SIT ON THE CHAIR!"],
      ["table", "🪑", "EAT AT THE TABLE!"],
      ["door", "🚪", "OPEN THE DOOR!"],
      ["window", "🪟", "LOOK OUT THE WINDOW!"],
      ["lamp", "💡", "TURN ON THE LAMP!"],
      ["book", "📚", "READ A BOOK!"],
      ["toy", "🧸", "PLAY WITH TOYS!"],
      ["ball", "⚽", "KICK THE BALL!"],
      ["phone", "📱", "RING RING!"],
      ["cup", "☕", "A LITTLE CUP!"],
      ["spoon", "🥄", "EAT WITH A SPOON!"],
      ["fork", "🍴", "EAT WITH A FORK!"],
      ["plate", "🍽️", "FOOD ON A PLATE!"],
      ["box", "📦", "WHAT IS IN THE BOX?"],
      ["key", "🔑", "THE KEY OPENS THE DOOR!"],
      ["clock", "🕐", "TICK TOCK!"],
      ["bath", "🛁", "SPLASH IN THE BATH!"],
      ["toilet", "🚽", "FLUSH THE TOILET!"],
    ]),
  },
  school: {
    label: "SCHOOL",
    icon: "🏫",
    kind: "words",
    items: pack([
      ["school", "🏫", "I GO TO SCHOOL!"],
      ["teacher", "👩‍🏫", "THE TEACHER HELPS US!"],
      ["student", "🧑‍🎓", "I AM A STUDENT!"],
      ["pencil", "✏️", "WRITE WITH A PENCIL!"],
      ["pen", "🖊️", "WRITE WITH A PEN!"],
      ["paper", "📄", "DRAW ON PAPER!"],
      ["desk", "🪑", "SIT AT YOUR DESK!"],
      ["bag", "🎒", "MY SCHOOL BAG!"],
      ["ruler", "📏", "MEASURE WITH A RULER!"],
      ["crayon", "🖍️", "COLOR WITH CRAYONS!"],
      ["glue", "🧴", "STICK WITH GLUE!"],
      ["scissors", "✂️", "CUT WITH SCISSORS!"],
      ["notebook", "📓", "WRITE IN YOUR NOTEBOOK!"],
      ["eraser", "🧽", "ERASE MISTAKES!"],
      ["computer", "💻", "CLICK ON THE COMPUTER!"],
    ]),
  },
  transport: {
    label: "CARS",
    icon: "🚗",
    kind: "words",
    items: pack([
      ["car", "🚗", "BEEP BEEP CAR!"],
      ["bus", "🚌", "THE BUS IS BIG!"],
      ["train", "🚆", "CHOO CHOO TRAIN!"],
      ["plane", "✈️", "THE PLANE FLIES HIGH!"],
      ["boat", "⛵", "SAIL THE BOAT!"],
      ["bike", "🚲", "PEDAL YOUR BIKE!"],
      ["truck", "🚚", "THE TRUCK CARRIES STUFF!"],
      ["taxi", "🚕", "YELLOW TAXI!"],
      ["helicopter", "🚁", "THE HELICOPTER SPINS!"],
      ["rocket", "🚀", "BLAST OFF!"],
      ["ship", "🚢", "BIG SHIP ON THE SEA!"],
      ["motorcycle", "🏍️", "VROOM MOTORCYCLE!"],
      ["ambulance", "🚑", "NEE NAW AMBULANCE!"],
      ["fire truck", "🚒", "FIRE TRUCK SAVES THE DAY!"],
      ["police car", "🚓", "POLICE CAR!"],
    ]),
  },
  nature: {
    label: "NATURE",
    icon: "🌳",
    kind: "words",
    items: pack([
      ["sun", "☀️", "THE SUN IS BRIGHT!"],
      ["moon", "🌙", "THE MOON AT NIGHT!"],
      ["star", "⭐", "TWINKLE TWINKLE STAR!"],
      ["cloud", "☁️", "FLUFFY CLOUD!"],
      ["rain", "🌧️", "PITTER PATTER RAIN!"],
      ["snow", "❄️", "COLD WHITE SNOW!"],
      ["wind", "💨", "WHOOSH GOES THE WIND!"],
      ["tree", "🌳", "TALL GREEN TREE!"],
      ["flower", "🌸", "PRETTY FLOWER!"],
      ["grass", "🌿", "SOFT GREEN GRASS!"],
      ["rock", "🪨", "HARD ROCK!"],
      ["river", "🏞️", "THE RIVER FLOWS!"],
      ["sea", "🌊", "BIG BLUE SEA!"],
      ["beach", "🏖️", "SANDY BEACH!"],
      ["mountain", "⛰️", "TALL MOUNTAIN!"],
      ["forest", "🌲", "TREES IN THE FOREST!"],
      ["leaf", "🍃", "A GREEN LEAF!"],
      ["rainbow", "🌈", "COLORS IN THE SKY!"],
      ["lightning", "⚡", "ZAP LIGHTNING!"],
      ["fire", "🔥", "HOT FIRE!"],
    ]),
  },
  shapes: {
    label: "SHAPES",
    icon: "⬛",
    kind: "words",
    items: pack([
      ["circle", "⭕", "A ROUND CIRCLE!"],
      ["square", "⬛", "FOUR SIDES ON A SQUARE!"],
      ["triangle", "🔺", "A TRIANGLE HAS THREE CORNERS!"],
      ["rectangle", "▭", "A LONG RECTANGLE!"],
      ["oval", "🥚", "AN OVAL EGG SHAPE!"],
      ["diamond", "💎", "A SHINY DIAMOND!"],
      ["heart", "❤️", "A HEART SHAPE!"],
      ["line", "➖", "A STRAIGHT LINE!"],
    ]),
  },
  toys: {
    label: "TOYS",
    icon: "🧸",
    kind: "words",
    items: pack([
      ["doll", "🪆", "CUDDLE THE DOLL!"],
      ["teddy", "🧸", "TEDDY BEAR HUG!"],
      ["blocks", "🧱", "STACK THE BLOCKS!"],
      ["puzzle", "🧩", "FIT THE PUZZLE!"],
      ["kite", "🪁", "FLY A KITE!"],
      ["balloon", "🎈", "POP THE BALLOON!"],
      ["drum", "🥁", "BANG THE DRUM!"],
      ["guitar", "🎸", "STRUM THE GUITAR!"],
      ["piano", "🎹", "PLAY THE PIANO!"],
      ["robot", "🤖", "BEEP BOOP ROBOT!"],
      ["train toy", "🚂", "TOY TRAIN CHUGS!"],
      ["car toy", "🚙", "VROOM TOY CAR!"],
      ["slide", "🛝", "WHEEE DOWN THE SLIDE!"],
      ["swing", "🪢", "SWING HIGH!"],
    ]),
  },
  actions: {
    label: "ACTIONS",
    icon: "🏃",
    kind: "words",
    items: pack([
      ["run", "🏃", "RUN FAST!"],
      ["walk", "🚶", "WALK SLOWLY!"],
      ["jump", "🦘", "JUMP UP HIGH!"],
      ["sit", "🪑", "SIT DOWN!"],
      ["stand", "🧍", "STAND UP TALL!"],
      ["sleep", "😴", "GO TO SLEEP!"],
      ["eat", "🍽️", "EAT YOUR FOOD!"],
      ["drink", "🥤", "DRINK WATER!"],
      ["play", "🎮", "LET US PLAY!"],
      ["read", "📖", "READ A STORY!"],
      ["draw", "🎨", "DRAW A PICTURE!"],
      ["sing", "🎤", "SING A SONG!"],
      ["dance", "💃", "DANCE AND SPIN!"],
      ["swim", "🏊", "SWIM IN THE POOL!"],
      ["climb", "🧗", "CLIMB UP!"],
      ["throw", "🤾", "THROW THE BALL!"],
      ["catch", "🤲", "CATCH IT!"],
      ["kick", "⚽", "KICK THE BALL!"],
      ["wash", "🧼", "WASH YOUR HANDS!"],
      ["brush", "🪥", "BRUSH YOUR TEETH!"],
    ]),
  },
  feelings: {
    label: "FEELINGS",
    icon: "😊",
    kind: "words",
    items: pack([
      ["happy", "😊", "I FEEL HAPPY!"],
      ["sad", "😢", "I FEEL SAD!"],
      ["angry", "😠", "I FEEL ANGRY!"],
      ["scared", "😨", "I FEEL SCARED!"],
      ["tired", "😫", "I AM TIRED!"],
      ["hungry", "😋", "I AM HUNGRY!"],
      ["thirsty", "🥤", "I AM THIRSTY!"],
      ["silly", "🤪", "I AM SILLY!"],
      ["proud", "😌", "I FEEL PROUD!"],
      ["love", "🥰", "I LOVE YOU!"],
    ]),
  },
  weather: {
    label: "WEATHER",
    icon: "🌤️",
    kind: "words",
    items: pack([
      ["sunny", "☀️", "IT IS SUNNY TODAY!"],
      ["cloudy", "☁️", "IT IS CLOUDY!"],
      ["rainy", "🌧️", "IT IS RAINY!"],
      ["snowy", "🌨️", "IT IS SNOWY!"],
      ["windy", "💨", "IT IS WINDY!"],
      ["storm", "⛈️", "BIG STORM!"],
      ["hot", "🥵", "IT IS HOT!"],
      ["cold", "🥶", "IT IS COLD!"],
      ["warm", "🌡️", "NICE AND WARM!"],
      ["cool", "🧊", "NICE AND COOL!"],
    ]),
  },
  time: {
    label: "TIME",
    icon: "🕐",
    kind: "words",
    items: pack([
      ["day", "🌞", "THE DAY IS BRIGHT!"],
      ["night", "🌙", "GOOD NIGHT!"],
      ["morning", "🌅", "GOOD MORNING!"],
      ["today", "📅", "TODAY IS FUN!"],
      ["tomorrow", "⏭️", "SEE YOU TOMORROW!"],
      ["yesterday", "⏮️", "YESTERDAY WAS YESTERDAY!"],
      ["week", "📆", "SEVEN DAYS IN A WEEK!"],
      ["year", "🎆", "HAPPY NEW YEAR!"],
      ["birthday", "🎂", "HAPPY BIRTHDAY!"],
    ]),
  },
  places: {
    label: "PLACES",
    icon: "🗺️",
    kind: "words",
    items: pack([
      ["park", "🏞️", "PLAY IN THE PARK!"],
      ["zoo", "🦁", "ANIMALS AT THE ZOO!"],
      ["farm", "🚜", "ANIMALS ON THE FARM!"],
      ["store", "🏪", "SHOP AT THE STORE!"],
      ["hospital", "🏥", "DOCTORS AT THE HOSPITAL!"],
      ["library", "📚", "BOOKS AT THE LIBRARY!"],
      ["playground", "🛝", "FUN AT THE PLAYGROUND!"],
      ["kitchen", "🍳", "COOK IN THE KITCHEN!"],
      ["garden", "🌻", "FLOWERS IN THE GARDEN!"],
      ["street", "🛣️", "CARS ON THE STREET!"],
      ["city", "🏙️", "TALL BUILDINGS IN THE CITY!"],
      ["space", "🌌", "STARS IN SPACE!"],
      ["beach", "🏖️", "SAND AND WAVES!"],
      ["museum", "🏛️", "LOOK AT THE MUSEUM!"],
      ["airport", "🛫", "PLANES AT THE AIRPORT!"],
    ]),
  },
  sports: {
    label: "SPORTS",
    icon: "⚽",
    kind: "words",
    items: pack([
      ["soccer", "⚽", "KICK THE SOCCER BALL!"],
      ["basketball", "🏀", "BOUNCE BASKETBALL!"],
      ["tennis", "🎾", "HIT THE TENNIS BALL!"],
      ["baseball", "⚾", "THROW BASEBALL!"],
      ["football", "🏈", "RUN WITH FOOTBALL!"],
      ["golf", "⛳", "HIT THE GOLF BALL!"],
      ["swimming", "🏊", "SWIM IN THE POOL!"],
      ["skating", "⛸️", "GLIDE ON ICE!"],
      ["skiing", "⛷️", "SKI DOWN THE HILL!"],
      ["running", "🏃", "RUN A RACE!"],
      ["yoga", "🧘", "STRETCH AND BREATHE!"],
      ["boxing", "🥊", "BOXING GLOVES!"],
      ["volleyball", "🏐", "BUMP THE VOLLEYBALL!"],
      ["hockey", "🏒", "HOCKEY ON ICE!"],
      ["cycling", "🚴", "RIDE YOUR BIKE!"],
    ]),
  },
  jobs: {
    label: "JOBS",
    icon: "👷",
    kind: "words",
    items: pack([
      ["doctor", "👩‍⚕️", "DOCTORS HELP PEOPLE!"],
      ["nurse", "💉", "NURSES ARE KIND!"],
      ["firefighter", "👨‍🚒", "FIREFIGHTERS ARE BRAVE!"],
      ["police", "👮", "POLICE KEEP US SAFE!"],
      ["chef", "👨‍🍳", "CHEFS COOK FOOD!"],
      ["farmer", "👨‍🌾", "FARMERS GROW FOOD!"],
      ["pilot", "👨‍✈️", "PILOTS FLY PLANES!"],
      ["driver", "🚕", "DRIVERS STEER CARS!"],
      ["builder", "👷", "BUILDERS MAKE HOUSES!"],
      ["artist", "👩‍🎨", "ARTISTS PAINT PICTURES!"],
      ["singer", "🎤", "SINGERS SING SONGS!"],
      ["vet", "🐾", "VETS HELP ANIMALS!"],
    ]),
  },
};
